- docs/data/destinations/thetradedesk-cohort.md
I added a note to answer of future inquiry from customers about the cohort size difference between Amplitude and TheTradeDesk.
> AMP-84891 added a note for cohort size difference between amplitude and TTD

- docs/experiment/sdks/javascript-sdk.md
quick update to js dsk docs
ASAP
> update exp js sdk doc with serverZone config

- mkdocs.yml
Removing the Accessibe widget. We aren't using it as a company any longer, and both Legal and design gave it the go ahead to remove.
> Remove Accessibe

- docs/analytics/apis/user-privacy-api.md
Update the description of the Privacy API's `include_mapped_user_ids` parameter to explicity mention that this flag does not delete 
mapped user IDs.
> Update include_mapped_users description

- docs/experiment/sdks/react-native-sdk-legacy.md
- mkdocs.yml
Renames the old Experiment React Native SDK to include `(legacy)` in the title.
Also fixed NPM badge image link.
> [DDI-438] Fix Experiment RN legacy naming and badge

- docs/experiment/apis/management-api/api-beta.md
- docs/experiment/apis/management-api/experiments.md
- docs/experiment/apis/management-api/flags.md
Update documentation for MGT API. [SKY-3483](https://amplitude.atlassian.net/browse/SKY-3483)
[SKY-3483]: https://amplitude.atlassian.net/browse/SKY-3483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SKY-3483 update props syntax

- docs/data/destinations/snowflake.md
Snowflake Export Schema is outdated and not accurate. I am removing some deprecated fields which no longer got exported, and then fix the data types to match with the actual Snowflake export.
ASAP, but no real deadline
[AMP-87569]: https://amplitude.atlassian.net/browse/AMP-87569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AMP-87569 Fix outdated Snowflake Export Schema

- docs/data/destinations/bigquery.md
Remove deprecated fields from BigQuery export schema and other minor fix. See https://community.amplitude.com/announcements-56/deprecating-fields-from-the-export-data-format-1850 for the deprecation announcement.
ASAP, but no real deadline
> AMP-87647 Remove deprecated fields from BigQuery export schema

- docs/analytics/apis/user-privacy-api.md
A customer pointed out that the API for DELETE doesn't make sense. They are correct. See: https://discourse.amplitude.com/t/documentation-on-user-privacy-api-is-self-conflicting/12238.
> Update user-privacy-api.md to reflect real use of DELETE

- docs/data/sdks/android/index.md
- docs/data/sdks/sdk-quickstart.md
https://amplitude.atlassian.net/browse/AMP-88654
I was able to retrieve carrier information without the READ_PHONE_STATE permission.
I looked at [the DeviceInfo we retrieve](https://github.com/amplitude/Amplitude-Android/blob/4e37e0f2d21c437af2b4f4bb58520b061a21a2be/src/main/java/com/amplitude/api/DeviceInfo.java#L114-L122) and it seems most can be done without the extra permission.
For carrier we use [TelephonyManager.getNetworkOperatorName()](https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkOperatorName()) which has no required permissions.
As far as I can tell the only thing that requires extra permissions is getting the Advertising ID.
[AMP-88654]: https://amplitude.atlassian.net/browse/AMP-88654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
> AMP-88654 remove outdated READ_PHONE_STATE permission warning

- docs/analytics/apis/aliasing-api.md
We have added a new GET api for user mappings. See: https://amplitude.atlassian.net/jira/software/c/projects/AMP/boards/86?assignee=60073f9074c3e200715d3d64&selectedIssue=AMP-86909 
Adding it into the documentation so customers may use it.
> Update aliasing-api.md to reflect new GET endpoint

- overrides/partials/integrations/analytics/amplitude.html
- Add script
- Update script and add sampleRate
This PR adds Session Replay to Dev Docs. Initial sample rate is 50%
> Instrument Session Replay

- docs/analytics/apis/taxonomy-api.md
- docs/data/destinations/google-ads-event-streaming.md
- Add link to google service account docs
- Add note about taxonomy api access
Adds a note to make more clear the account requirements of the Taxonomy API. DDI-443
> DDI 443 taxonomy api

- docs/data/destinations/google-ads-event-streaming.md
Adds a link to Google's documentation about creating service accounts. Addresses #68. Will not add instructions directly, as we don't 
want to maintain documentation for another company's product.
> Add link to google service account docs

- docs/data/sources/amazon-s3.md
- docs/data/sources/bigquery.md
- docs/data/sources/google-cloud-storage.md
- docs/data/sources/snowflake.md
Add additional property docs to Snowflake/BigQuery/S3/GCS, which was missing/wrong, hence result in we silently drop additional properties from customer's import.
ASAP but not urgent
> AMP-88309 Add additional property docs to Snowflake/BigQuery/S3/GCS

- docs/experiment/sdks/php-sdk.md
Update Experiment PHP docs with assignment tracking
> Update Experiment PHP docs with assignment tracking

- .github/styles/Amplitude/Headings.yml
- docs/session-replay/index.md
- docs/session-replay/sdks/index.md
- docs/session-replay/sdks/plugin.md
- docs/session-replay/sdks/standalone.md
- docs/stylesheets/extra.css
- includes/session-replay/browsers.md
- includes/session-replay/data-retention.md
- includes/session-replay/eu-data-residency.md
- includes/session-replay/known-limitations.md
- includes/session-replay/mask-onscreen-data.md
- includes/session-replay/performance.md
- includes/session-replay/replay-storage.md
- includes/session-replay/sampling-rate.md
- includes/session-replay/user-opt-out.md
- mkdocs.yml
- Init and stub out content
- Update to standalone doc, css, and vale rule
- quick grammar update
- Plugin SDK doc
Docs (Standalon and Plugin) for instrumenting Session Replay
> DDI 442 Session Replay

- docs/experiment/sdks/nodejs-sdk.md
- docs/experiment/sdks/python-sdk.md
Update suggested fetch and evaluate usage to the new v2 methods for node and python SDKs.
V1 methods still work as before, but are deprecated.
As soon as possible
> udpate exp node and python sdks to use eval/fetch v2

- docs/data/sdks/android/index.md
- docs/data/sdks/ios/index.md
- includes/sdk-set-offline.md
From discourse: https://discourse.amplitude.com/t/limits-on-offline-event-capture/12221/19?u=justin
* Add information about setOffline() method to Android & iOS (maintenance) SDK docs
* https://pr-122.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios/#offline-mode
* https://pr-122.d19s7xzcva2mw3.amplifyapp.com/data/sdks/android/#offline-mode
> AMP-90580 Add offline documentation to Android & iOS SDKs

- docs/data/sdks/android-kotlin/index.md
- docs/data/sdks/ios-swift/index.md
Correct mobile SDKs' tracking options.
Swift SDK has 14 options while Kotlin SDK has 18 in total.
They share 13 same options. 
Swift can disable idfv, while Kotlin can disable `adid`, `appSetId`, `apiLevel`, `latLng`, and `deviceBrand`
Also notice that Swift uses `disableTrackXxxx()` format while Kotlin uses `disableXxxx()`. 
> Update mobile SDKs tracking options

- docs/data/destinations/braze.md
Add Email as an identifier option for Braze event streaming and link to Braze documentation FAQ to point out some caveats
> add email as Braze event streaming identifier option

- docs/analytics/apis/user-profile-api.md
Profile API will have throttling soon -- default to 600 TPM (Time per minute) and customize for existing heavy users. 
Feature is tracked on JIRA: https://amplitude.atlassian.net/browse/AMP-87063  and will roll out later. 
Thus prepare a doc update so later I can merge this when we enable the feature. 
Add 2nd owner + PM to be aware of changes. 
N/A. Late Nov or Dec,  this feature is in dryrun mode to ensure smooth customer experience. JIRA: https://amplitude.atlassian.net/browse/AMP-87063 
> AMP-87063 Profile API update throttling limit

- docs/data/sdks/go/ampli.md
feel free to change the language here, but essentially groups don't work on the Go SDK, so the section should be removed and updated with a warning panel instead.
Confirmed with Engineering that Groups are not supported via Go SDK: https://discourse.amplitude.com/t/unable-to-instrument-groups-using-ampli-go-sdk/12567/4 
> Update Groups snippet on docs

- docs/data/sources/amazon-s3.md
- docs/data/sources/google-cloud-storage.md
Thanks to @Rox Chang's testing, the correct requirement is Admin or Manager. This PR is to update dev doc to reflect this.
> AMP-91670 Correct the role requirement in dev doc for S3 and GCS

- docs/data/sdks/android-kotlin/index.md
The protection level of [ACCESS_NETWORK_STATE](https://developer.android.com/reference/android/Manifest.permission#ACCESS_NETWORK_STATE) is [normal](https://developer.android.com/guide/topics/permissions/overview#normal) which is granted by the system automatically and cannot be changed on Android 6+
https://developer.android.com/guide/topics/manifest/permission-element.html
https://source.android.com/docs/core/permissions/runtime_perms#affected-permissions
> fix: Update Kotlin offline mode

- docs/experiment/apis/management-api/index.md
- docs/experiment/apis/management-api/versions.md
- mkdocs.yml
Added an endpoint for getting all versions of all flags and experiments that a management api key has access to, with specified time ranges and pagination options. This endpoint returns both flags and experiments versions. 
Ideally, before end of week. 
> SKY-4308 Add versions endpoint

- docs/experiment/apis/management-api/experiments.md
- docs/experiment/apis/management-api/flags.md
- Add documentation about a new API 
- Update documentation for an existing API
[SKY-4389](https://amplitude.atlassian.net/browse/SKY-4389)
Once we deploy API changes.
[SKY-4389]: https://amplitude.atlassian.net/browse/SKY-4389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SKY-4389 update user inclusions and target segments docs

- docs/session-replay/index.md
- docs/session-replay/sdks/plugin.md
- docs/session-replay/sdks/standalone.md
Add notes to Overview, Plugin, and Standalone that explicitly mention that Session Replay isn't enabled by default, and requires additional setup.
ASAP
> DDI-452 Add note that SR isn't on by default

- docs/data/destinations/appsflyer.md
Appsflyer is changing the way they allow customers to use the ket for their event streaming integration. In this PR, updated Appsflyer docs for using s2s key instead of dev key. Refer: [Appsflyer docs](https://www.docs.developers.amplitude.com/data/destinations/appsflyer/#configure-event-forwarding)
Can be merged anytime from (02/08/24). Preferably by end of week (02/11/24)
> AMP-90669 [event-streaming] Updated appsflyer docs for s2s key

- includes/sdk-ts-browser/shared-csp.md
Quick start guide links are flaky. Replace the link with the one to github which is more stable.  
> Fix: Browser SDK CSP script loader link

- docs/session-replay/sdks/plugin.md
- docs/session-replay/sdks/standalone.md
- docs/session-replay/tag-managers/google-tag-manager.md
- mkdocs.yml
> DDI-457 Session Replay Updates

- docs/experiment/sdks/javascript-sdk.md
- docs/experiment/sdks/php-sdk.md
Update Experiment PHP SDK with AssignmentTrackingProvider docs
> Update Experiment PHP SDK with AssignmentTrackingProvider docs

- docs/analytics/domain-proxy.md
While configuring a Domain Proxy to relay events, I found that the provided cURL example does not work as intended. The issue lies with the use of the `--data-urlencode` option, which is designed for encoding query string parameters rather than sending JSON data in the request body. This results in the JSON being encoded in a manner that the server may not interpret as valid JSON.
ASAP
> Update curl exmple

- docs/analytics/apis/user-profile-api.md
From customer ticket: https://discourse.amplitude.com/t/user-profile-api-looking-for-suggestions-on-retrieving-recommendation-via-user-profile-api/12559/8
The 100,000 limit on recommendation was old day -- never being hit. 
The 600 limit on all paths were introduced in Jan 2024 (by checking most customer usage) --> it will void 100,000 recommendations given it is more restrict. 
Thus to avoid confusion to customers, just remove old throttling limit on our doc. 
> AMP-93651 Profile API update throttling limit

- docs/session-replay/index.md
- docs/session-replay/sdks/standalone.md
DDI-462: Customers can become confused about when to use the standalone SDK. Broadened the messaging around when to use the Standalone.
> DDI-462 Broaden use case for Standalone SDK

- docs/experiment/apis/evaluation-api.md
Minor improvement to the dev docs to make things that happen underneath the hood a bit more transparent. 
Addressing this Discourse question.
https://discourse.amplitude.com/t/experiments-exposure-events-not-triggering/12144
> Adding a note regarding auto assignment tracking when using REST API

- docs/data/sdks/typescript-node/index.md
- includes/sdk-ts/shared-ts-configuration.md
This PR fixes the typo mistake `reties` with `retries` in couple of README files. It also removes duplicated words `instead of`.
> Fix the typos in README files

- mkdocs.yml
Removing the duplicate link for Kochava under Others because it's already under Attribution.
We have two entries for Kochava in the index tree. One is correctly filed under Attribution while the other one is a duplicate currently filed under Other. This change removes the duplicate and keeps the main link.
N/A
> Update mkdocs.yml to remove duplicate Kochava entry from under Other

- docs/data/sdks/ios-swift/index.md
"You can adjust the time window for which sessions are extended. The default session expiration time is 30 minutes."
updated to
"You can adjust the time window for which sessions are extended. The default session expiration time is 5 minutes."
> Update index.md to correct the default session expiration time

- docs/session-replay/sdks/plugin.md
Forgot that the restart of replay collection also changes with the SDK
> Plugin restart replay collection update

- docs/session-replay/sdks/plugin-android.md
- mkdocs.yml
Added support for global variables with [mkdocs-markdownextradata-plugin](https://github.com/rosscdh/mkdocs-markdownextradata-plugin).
Store variables in the `extra:` array in `mkdocs.yml` and wrap them in `@{$ ... $}` to reference them in content.
For example:
```
android:
session_replay:
plugin:
version: 0.5+
```
resolves to `@{$ android.session_replay.plugin.version $}`
> Add support for globals

- docs/data/sdks/flutter/migration.md
- mkdocs.yml
Add migration guide for the new Flutter SDK 4.0. 
It will not shown on the navigation bar but can be accessed by https://pr-239.d19s7xzcva2mw3.amplifyapp.com/data/sdks/flutter/migration.
Do **NOT** merge this until the beta version is released at https://github.com/amplitude/Amplitude-Flutter/pull/179
> Add Flutter SDK migration guide

- includes/sdk-ts/shared-ts-configuration.md
Remove `config.transportProvider` from Browser 2.x
- It's hidden in Browser 2.x https://github.com/amplitude/Amplitude-TypeScript/blob/790311c1286237c9e081789789b2693a5d67160e/packages/analytics-types/src/config/browser.ts#L60C1-L63C95. 
- It's configurable in Browser 1.x https://github.com/amplitude/Amplitude-TypeScript/blob/1d08e7d07c782a722837857b81e49f00c643f697/packages/analytics-types/src/config/browser.ts#L55C1-L57C2
> fix: remove transportProvider from Browser 2.x

- docs/session-replay/sdks/standalone-android.md
* fix: add flush() to standalone Android session replay example
> fix: add flush() to standalone Android session replay example

- docs/session-replay/sdks/plugin-android.md
- docs/session-replay/sdks/standalone-android.md
*  improved flush() docs in to standalone Android session replay
> fix: improved flush() docs in to standalone Android session replay

- docs/data/sources/snowflake.md
Update Snowflake CDC migration steps to mention that once Change Tracking is enabled, at least one job should be complete with the existing configuration to prevent failures to determine the data drift
March 12, 2024
> AMP-91204 Update Snowflake CDC migration steps

- docs/data/sdks/typescript-browser/migration.md
Migrating to the Amplitude SDK 2.0 will cause the breaking of changes. We have a lot of customers didn't aware of the changes, especially for the web attribution part. Even if we have a behavior comparison at the end of this doc, we want to bring more attention. 
> AMP-96376 - Add breaking changes warning in the migration guide to bring attention

- docs/analytics/apis/user-profile-api.md
See this request: https://amplitude.atlassian.net/browse/AMP-90198
customers/CSM wants the limit to be documented in dev doc, thus add the note section. 
No hard deadline
> AMP-90198 add max number of recommend items Profile API can return

- docs/experiment/apis/management-api/experiments.md
DONT MERGE THIS IN UNTIL WE ACTUALLY RELEASE MULTI ARM BANDIT WHICH IS MAYBE END OF QUARTER MAYBE Q1 2024. 
I am just writing this up otherwise I will forget about this.
Here is the code change https://github.com/amplitude/javascript/pull/34707/files
> SKY-3994 update experiment type

- docs/robots.txt
We've added the noindex meta to the JS docs page so these attributes are no longer needed
> fix: remove javascript sdk paths from robots.txt

- includes/session-replay/mask-onscreen-data-android.md
Renamed Modifier.mask().unmask().block() to Modifier.ampMask().ampUnmask().ampBlock() to prevent potential namespacing issues
> fix: add prefixes to SR Modifier functions

- docs/analytics/apis/user-profile-api.md
- docs/data/destinations/webhooks-streaming.md
Update Profile API doc that for computation ID we also support it. 
On another path (prediction) it was already mentioned we supported it: https://www.docs.developers.amplitude.com/analytics/apis/user-profile-api/#get-singlemultiple-prediction-propensity --> thus for this I copy the section data to explain how multiple computations are supported. 
> AMP-91621 update Profile API dev doc on multiple computation IDs support

- docs/session-replay/sdks/middleware-android.md
- docs/session-replay/sdks/plugin-android.md
- docs/session-replay/sdks/standalone-android.md
- includes/session-replay/bitmap-capture-android.md
- mkdocs.yml
* Add Bitmap capture instructions to Android SR docs
> feat: add bitmap-capture-android.md to Session Replay docs

- docs/analytics/apis/lookup-tables-api.md
- docs/data/apis/lookup-tables-api.md
- docs/data/sources/lookup-table.md
- includes/api-table-analytics.md
- includes/auth-basic.md
- mkdocs.yml
Added docs for the new Lookup Table API V3, which is under data-api, so moved to the Data section.
> AMP-96489 Add new docs for lookup table apis v3

- docs/session-replay/tag-managers/google-tag-manager.md
We need the plugin to be added to the window before Amplitude is ready, so that the plugin can check against the Admin UI's sample rate. this change in steps and initialization triggers ensures the plugin is ready in the window
> Update SR Plugin with Promise to GTM doc
