amplitude/amplitude-dev-center

docs/analytics/apis/behavioral-cohorts-api.md
Remove beta label for this features so all other customers can get it. (Related internal PR to remove whitelist https://github.com/amplitude/amplitude/pull/22173) 
Also add a sample response as some customers ask for it, so this can help to clarify them. Add our PM Brandon so he is aware of the change mostly. 
=> AMP-85448 cohort API remove beta label + add sample response

docs/data/destinations/marketo-static-list-cohort.md
=> [DDI-434]Sentence rewrite

.github/styles/Amplitude/ComplexWords.yml, .github/styles/Amplitude/Exclamation.yml, .github/styles/Amplitude/FirstPerson.yml, .github/styles/Amplitude/HeadingPunctuation.yml, .github/styles/Amplitude/Headings.yml, .github/styles/Amplitude/Latin.yml, .github/styles/Amplitude/Passive.yml, .github/styles/Amplitude/TooWordy.yml, .github/styles/Amplitude/Will.yml, docs/utils/vale-test.md
=> Update vale rules

docs/data/sdks/android-kotlin/index.md, docs/data/sdks/android/index.md, docs/data/sdks/ios-swift/index.md, docs/data/sdks/ios/index.md
https://amplitude.atlassian.net/browse/AMP-86273
=> feat: add min versions for mobile SDKs

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/sdks/ios-sdk.md, docs/experiment/sdks/javascript-sdk.md
=> ios local evaluation

docs/data/sdks/ios-swift/migration.md
Update iOS migration docs to include Obj-C snippets.
=> AMP-85993 Update iOS migration docs to include Obj-C snippets

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/sdks/javascript-sdk.md, docs/experiment/sdks/react-native-sdk.md
SDK doc update for react native client-side local evaluation
(Tuesday)
=> react native local evaluation

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/sdks/android-sdk.md, docs/experiment/sdks/javascript-sdk.md
Local evaluation documentation for android. 
Today
=> android local evaluation

docs/data/destinations/bigquery.md, docs/data/destinations/snowflake.md, docs/data/sources/bigquery.md, docs/data/sources/snowflake.md
Add the missing EU IP address for Snowflake/BigQuery
This is a bug fix for AMP-86494
=> AMP-86808 Add the missing EU IP address for Snowflake/BigQuery

.github/styles/Amplitude/Headings.yml, docs/data/tutorials/migrating-from-google-analytics/index.md, mkdocs.yml
Updates the Migrating to Amplitude from Google Analytics to reformat and add additional context
=> [DDI-437] Update Migrating from Google Analytics doc

docs/data/destination-cohort-overview.md, docs/data/destination-event-streaming-overview.md
Add IP range for CDP cohort sync & event streaming help doc
N/A
=> AMP-87690 Add IP range for CDP related help doc

docs/data/sources/snowflake.md
=> DDI-441 typo and cleanup

docs/robots.txt
=> add utils folder to robots

docs/data/destinations/cohort-webhooks.md
=> Update beta message

docs/data/destinations/clevertap-event-streaming.md, docs/data/destinations/extole-event-streaming.md, docs/data/destinations/hubspot-event-streaming.md, docs/data/destinations/kameleoon-event-streaming.md, docs/data/destinations/lantern-event-streaming.md, docs/data/destinations/moengage-event-streaming.md, docs/data/destinations/planhat-event-streaming.md, docs/data/destinations/plotline-cohort.md, docs/data/destinations/plotline-event-streaming.md, docs/data/destinations/statsig.md, docs/data/destinations/userlist-cohort.md, docs/data/destinations/userlist-event-streaming.md
Update the beta tags in docs.
Ticket: https://amplitude.atlassian.net/browse/AMP-77893
Remove the beta tag on a number of docs to make the product seem less "beta".
Fails with `ERROR   -  Config value 'plugins': The "git-revision-date-localized" plugin is not installed` even though plugin installed. I did check each page in the Amplify preview provided by CI.
=> AMP-77893 [integrations] update beta tags in docs

docs/experiment/sdks/android-sdk.md, docs/experiment/sdks/ios-sdk.md, docs/experiment/sdks/javascript-sdk.md, docs/experiment/sdks/react-native-sdk.md
=> update exp client-side sdk docs with updated fetch on start info

docs/all-resources.md
=> Correct link to Amplitude developer workspace on Postman

docs/experiment/general/evaluation/local-evaluation.md, docs/experiment/sdks/php-sdk.md
Update Experiment PHP SDK page with local evaluation docs
=> Update with Experiment PHP local evaluation docs

docs/getting-started.md
Update old link to HC Getting Started -> HC Start Here.
=> Update HC getting started link

docs/data/sdks/browser-2/index.md
docs: update doc for ts v2 about disable cookie
=> docs: update doc for ts v2 about disable cookie

docs/experiment/apis/evaluation-api.md
Added regional URLs to Evaluation API. Resolves #81.
=> [#81] Add Region API URLs to Evaluation API

docs/experiment/sdks/php-sdk.md
Update Experiment PHP docs with AmplitudeCookie util
=> Update Experiment PHP docs with AmplitudeCookie util

overrides/main.html
- Reinitialize Kapa widget
- Remove experiment code
=> kapa go live

overrides/main.html
=> Reformat last seed question

docs/data/destinations/bigquery.md
[AMP-89630]: https://amplitude.atlassian.net/browse/AMP-89630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AMP-89630 Better format on multiple BigQuery roles needed

docs/experiment/sdks/nodejs-sdk.md
Fixed broken code example rasied by AllTrails.
=> DDI-444 Fixed typo in code

docs/data/destinations/braze-cohort.md
=> Fix list formatting in Braze Cohort Prereq

docs/experiment/sdks/php-sdk.md
Fix Experiment PHP SDK code example type
=> Fix Experiment PHP SDK code example type

docs/experiment/sdks/nodejs-sdk.md
Update Experiment Node evaluateV2 code examples
=> Update Experiment Node evaluateV2 code examples

docs/session-replay/sdks/plugin.md
=> Update plugin version

docs/experiment/sdks/go-sdk.md
=> update experiment golang local eval docs to v2

includes/data-sources-sdks-client-side.md, includes/data-sources-sdks.md
Removing beta from iOS library
=> AMP-91871: Remove beta from ios library

docs/guides/accounts-instrumentation-guide.md, docs/guides/adobe-migration-guide.md, docs/guides/amplitude-keys-guide.md, docs/guides/cookies-consent-mgmt-guide.md, docs/guides/index.md, docs/guides/mixpanel-migration-guide.md, docs/guides/mparticle-migration-guide.md, docs/guides/segment-migration-guide.md, mkdocs.yml
=> add adobe guide to nav

docs/data/sdks/android-kotlin/index.md
Add Android Kotlin configuration options. 
Can share the docs to the customer https://amplitude.atlassian.net/browse/AMP-91915
=> Update Android Kotlin SDK configurations

docs/data/sdks/browser-2/index.md
Add offline mode section for the new feature 
Add config 
=> add TS offline mode

docs/data/destinations/braze.md, docs/data/destinations/customerio.md, docs/data/destinations/google-analytics-4-firebase.md, docs/data/destinations/google-analytics-4-gtag.md, docs/data/destinations/intercom.md, docs/data/destinations/iterable.md
This feature has been updated to be "user update forwarding". We will now forward any user creation and property updates based the user's property selections. 
We are also re-enabling Braze user update forwarding as it had been disabled while waiting for this feature
In coordination with the UI release of this feature for Braze
=> Update Braze, Intercom, Iterable, GA4 and Customer.io user fowarding to reflect new changes to the feature

docs/data/destinations/snowflake-data-share.md, docs/data/destinations/snowflake.md
Add Snowflake Data Share setup steps and limitation sections.
=> AMP-92753 Add Snowflake Data Share setup steps and limitation

overrides/partials/integrations/analytics/amplitude.html
=> Update SR Plugin version

includes/session-replay/sampling-rate.md
Added detail around how to calculate a good sample rate when starting with Session Replay
=> DDI-450 Add context for session replay sample rate

includes/session-replay/sampling-rate.md
=> Update code sample

docs/experiment/sdks/php-sdk.md
Update docs for Experiment PHP enhancements 
=> Update docs for Experiment PHP enhancements 

docs/session-replay/sdks/plugin.md, docs/session-replay/sdks/standalone.md
=> [DDI-451] Added note about CSS style troubleshooting

includes/session-replay/data-retention.md
=> DDI-453 Add legal note about consent management

docs/experiment/apis/management-api/experiments.md, docs/experiment/apis/management-api/flags.md
Rename parameter.
Jira ticket: [SKY-4458](https://amplitude.atlassian.net/browse/SKY-4458)
[SKY-4458]: https://amplitude.atlassian.net/browse/SKY-4458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> update parameter name

docs/data/sdks/ios-swift/index.md
DON'T merge it until https://github.com/amplitude/Amplitude-Swift/pull/111 is merged and released
=> Add Swift SDK offline mode section

docs/guides/mixpanel-migration-guide.md
Added detail about the Mixpanel import tool.
1/24
=> Mixpanel Import Tool [DDI-446]

docs/data/sources/amazon-s3.md
Update the condition for insert_id
=> AMP-92930 Update the condition for insert_id

mkdocs.yml
=> Add option to reject all from cookie banner

mkdocs.yml
=> Update cookie consent message

mkdocs.yml
=> fix double phrasing

docs/data/destinations/amazon-s3.md, docs/data/destinations/azure-blob-storage.md, docs/data/destinations/bigquery.md, docs/data/destinations/google-cloud-storage.md, docs/data/destinations/redshift.md, docs/data/destinations/snowflake-data-share.md, docs/data/destinations/snowflake.md
Adds a note about event filtering support for Data Warehouse and Cloud Storage destinations
March 1, 2024
=> AMP-92829 Add event filtering note for DWH and CS destinations

docs/data/sdks/ios-swift/migration.md
Updating details on how data gets migrated for ios apps that are not sandboxed
=> Amp 94508/udpate ios migration docs

docs/analytics/apis/ccpa-dsar-api.md
=> Update ccpa-dsar-api.md for python example

includes/sdk-migration/sdk-browser-2-migration/default-event-tracking.md
fix formInteraction to formInteractions
=> Fix typo about formInteractions

docs/data/sources/bigquery.md
minor spelling change
Minor spelling fix
ASAP
=> Updating BiqQuery to BigQuery

insiders.mkdocs.yml, mkdocs.yml, requirements.txt
Reverts amplitude/amplitude-dev-center#229
=> Revert "Update emoji engine from deprecated version"

docs/session-replay/sdks/plugin.md, includes/session-replay/data-retention.md, includes/session-replay/known-limitations.md
- [DDI-467]Update SR retention policy
- [DDI-468]Session Replay session definition limitation
- Update SR Plugin disable command
[DDI-467]: https://amplitude.atlassian.net/browse/DDI-467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DDI-468]: https://amplitude.atlassian.net/browse/DDI-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Session Replay Dev Doc Updates

docs/experiment/guides/getting-started/track-exposure.md, includes/experiment-interactive-evaluation-api-table.md, includes/experiment-interactive-exposure-table.md, includes/experiment-interactive-exposure-tracking-table.md, includes/experiment-interactive-fetch-table.md
Update interactive tables  with server zone config.
=> Update interactive tables  with server zone config

docs/session-replay/sdks/plugin-android.md, docs/session-replay/sdks/standalone-android.md, insiders.mkdocs.yml, mkdocs.yml, requirements.txt
* AMP-94894 - bump session replay alpha version
* fix: add mkdocs-markdownextradata-plugin to requirements.txt
=> bump session replay alpha version

docs/session-replay/sdks/plugin.md
=> DDI-469 Add detail to troubleshooting

docs/session-replay/sdks/plugin.md, mkdocs.yml
=> Bumb SR Browser Plugin version, and make it a variable

docs/data/ampli/integrating-with-ci.md
=> Fix Ampli code sample indentation

includes/experiment-interactive-evaluation-api-table.md
Fix experiment interactive table EU server zone link
=> Fix experiment interactive table EU server zone link

docs/data/sdks/browser-2/index.md
- [ x ] Doc update.
- [ x ] New documentation.
=> AMP-95395 - add marketing attribution tracking

docs/experiment/apis/management-api/api-beta.md, docs/experiment/apis/management-api/experiments.md, docs/experiment/apis/management-api/flags.md
We are updating types of supported operators, and therefore updating the docs.
After the feature goes live.
=> update documentation to match updated feature

docs/session-replay/sdks/plugin.md, mkdocs.yml
- Added requested doc updates
- incremented plugin version global to 1.1.0
=> [DDI-471]Update plugin doc for version 1.1.0

docs/experiment/sdks/nodejs-sdk.md
Added parameters for new SDK stream flag config changes feature. 
=> SKY-4507 Added docs about stream configs for nodejs sdk

.github/styles/Vocab/dev/accept.txt, docs/session-replay/sdks/plugin-android.md, docs/session-replay/sdks/standalone-android.md, includes/session-replay/known-limitations-android.md, includes/session-replay/mask-onscreen-data-android.md, includes/session-replay/performance-android.md, includes/session-replay/troubleshooting-android.md
Fixed a global variable syntax issue, added some edits.
=> Edits and fixes for SR Android

docs/analytics/apis/taxonomy-api.md
=> Update doc based on input from discourse

docs/session-replay/sdks/plugin.md, docs/session-replay/sdks/standalone.md, insiders.mkdocs.yml
- **Disable social plugin due to build failure**
=> disable social plugin

docs/session-replay/sdks/plugin.md, docs/session-replay/sdks/standalone.md, includes/session-replay/instrumentation-level.md
=> [DDI-474] Add detail that mentions SR is instrumented per project

docs/data/sources/databricks.md
Address the comments added in the PR https://github.com/amplitude/amplitude-dev-center/pull/194 after we have it merged.
=> AMP-96862 [DatabricksImport] Update the developer doc for databricks import

docs/data/sdks/browser-2/index.md
[Thread ](https://amplitude.slack.com/archives/C02E1H87E2C/p1712079024299769)
=> Update excludeReferrers language

docs/guides/accounts-instrumentation-guide.md
Request from slack.
@jessicachiuuu
=> Update workbook URL

docs/session-replay/index.md, includes/session-replay/browsers.md
=> DDI-480 and DDI-481: Add note about browser extensions and shadow DOM

docs/data/sdks/browser-2/deta.md
=> Remove detail about VT

docs/session-replay/sdks/middleware-android.md
* Improve flush docs for SR middleware
=> fix: update SR middleware docs to call out flush on close support

.github/styles/config/vocabularies/dev/accept.txt, docs/data/sdks/browser-2/deta.md
- **Change DETA to Autocapture**
- **DETA -> Autocapture, again**
=> deta autocapture

docs/data/sdks/browser-2/autocapture.md, mkdocs.yml
docs: update deta to autocapture
=> docs: update deta to autocapture

docs/data/sdks/browser-2/index.md, docs/robots.txt
Removing the legacy SDKs from robots.txt to remove confusion around the various SDKs for browser
=> chore: Update robots.txt and change page description

docs/guides/wordpress-plugin-guide.md
=> Add a link to the plugin's page

docs/robots.txt
Add noindex meta for javascript SDK pages
=> AMP-98496: Test out noindex

includes/ampli/flush/ampli-flush-section.md, includes/sdk-ts-browser/ampli.md
- **Add content for reset method**
- **Flush update**
Updates to reset and flush methods as requested in slack.
=> ampli updates

docs/data/sdks/browser-2/autocapture.md
Visual Tagger, Visual Tag Editor -> Visual Labeling
Dynamic Events -> Labeled Events
=> update naming as requested

docs/session-replay/tag-managers/google-tag-manager.md, mkdocs.yml
=> update SR browser plugin version

includes/session-replay/sampling-rate.md
- **update SR browser plugin version**
- **bump standalone version**
- **Mention initial sample rate and settings screen**
=> Mention SR initial sample rate and settings screen

docs/session-replay/tag-managers/google-tag-manager.md, mkdocs.yml
- **DDI-495 update version numbers**
- **DDI-492 add troubleshooting link**
=> DDI 495 and DDI-492

includes/sdk-ts-browser/marketing-analytics-overview.md
> utm medium description is wrong so i modify it
> Important but not urgent
- [O] Doc update.
=> modify utm medium description
